export const footerCategory = [
    {
        id: 1,
        colItem: [
            {
                id: 1,
                category: 'Thời trang nam',
                url: '',
                list: [
                    { id: 1, title: 'áo khoác', url: '' },
                    { id: 2, title: 'áo vest & blazer', url: '' },
                    { id: 3, title: 'áo hoodie, áo len & áo nỉ', url: '' },
                    { id: 4, title: 'quần jeans', url: '' },
                    { id: 5, title: 'quần dài/quần âu', url: '' },
                    { id: 6, title: 'quần short', url: '' },
                    { id: 7, title: 'áo', url: '' },
                    { id: 8, title: 'áo ba lỗ', url: '' },
                    { id: 9, title: 'đồ lót', url: '' },
                    { id: 10, title: 'đồ ngủ', url: '' },
                    { id: 11, title: 'đồ bộ', url: '' },
                    { id: 12, title: 'vớ/tất', url: '' },
                    { id: 13, title: 'trang phục truyền thống', url: '' },
                    { id: 14, title: 'đồ hóa trang', url: '' },
                    { id: 15, title: 'trang phục ngành nghề', url: '' },
                    { id: 16, title: 'khác', url: '' },
                    { id: 17, title: 'trang sức nam', url: '' },
                    { id: 18, title: 'kính mắt nam', url: '' },
                    { id: 19, title: 'thắt lưng nam', url: '' },
                    { id: 20, title: 'cà vạt & nơ cổ', url: '' },
                    { id: 21, title: 'phụ kiện nam', url: '' },
                ],
            },
            {
                id: 2,
                category: 'Nhà cửa và đời sống',
                url: '',
                list: [
                    { id: 1, title: 'chăn, ga, gối & nệm', url: '' },
                    { id: 2, title: 'đồ nội thất', url: '' },
                    { id: 3, title: 'trang trí nhà cửa', url: '' },
                    { id: 4, title: 'dụng cụ & thiết bị tiện ích', url: '' },
                    {
                        id: 5,
                        title: 'đồ dùng nhà bếp và hộp đựng thực phẩm',
                        url: '',
                    },
                    { id: 6, title: 'đèn', url: '' },
                    { id: 7, title: 'ngoài trời & sân vườn', url: '' },
                    { id: 8, title: 'đồ dùng phòng tắm', url: '' },
                    { id: 9, title: 'vật phẩm thờ cúng', url: '' },
                    { id: 10, title: 'đồ trang trí tiệc', url: '' },
                    { id: 11, title: 'chăm sóc nhà cửa và giặt ủi', url: '' },
                    { id: 12, title: 'sắp xếp nhà cửa', url: '' },
                    { id: 13, title: 'dụng cụ pha chế', url: '' },
                    { id: 14, title: 'tinh dầu thơm phòng', url: '' },
                    { id: 15, title: 'đồ dùng phòng ăn', url: '' },
                ],
            },
            {
                id: 3,
                category: 'Đồng hồ',
                url: '',
                list: [
                    { id: 1, title: 'đồng hồ nam', url: '' },
                    { id: 2, title: 'đồng hồ nữ', url: '' },
                    { id: 3, title: 'bộ đồng hồ & đồng hồ cặp', url: '' },
                    { id: 4, title: 'đồng hồ trẻ em', url: '' },
                    { id: 5, title: 'phụ kiện đồng hồ', url: '' },
                    { id: 6, title: 'khác', url: '' },
                ],
            },
            {
                id: 4,
                category: 'phụ kiện & trang sức nữ',
                url: '',
                list: [
                    { id: 1, title: 'nhẫn', url: '' },
                    { id: 2, title: 'bông tai', url: '' },
                    { id: 3, title: 'khăn choàng', url: '' },
                    { id: 4, title: 'găng tay', url: '' },
                    { id: 5, title: 'phụ kiện tóc', url: '' },
                    { id: 6, title: 'vòng tay & lắc tay', url: '' },
                    { id: 7, title: 'lắc chân', url: '' },
                    { id: 8, title: 'mũ', url: '' },
                    { id: 9, title: 'dây chuyền', url: '' },
                    { id: 10, title: 'kính mắt', url: '' },
                    { id: 11, title: 'kim loại quý', url: '' },
                    { id: 12, title: 'thắt lưng', url: '' },
                    { id: 13, title: 'và vạt & nơ cổ', url: '' },
                    { id: 14, title: 'phụ kiện thêm', url: '' },
                    { id: 15, title: 'bộ phụ kiện', url: '' },
                    { id: 16, title: 'vớ/ tất', url: '' },
                    { id: 17, title: 'ô/ dù', url: '' },
                ],
            },
            {
                id: 5,
                category: 'balo & túi ví nam',
                url: '',
                list: [
                    { id: 1, title: 'ba lô nam', url: '' },
                    { id: 2, title: 'ba lô laptop nam', url: '' },
                    { id: 3, title: 'túi & cặp đựng laptop', url: '' },
                    { id: 4, title: 'túi chống sốc laptop nam', url: '' },
                    { id: 5, title: 'túi tote nam', url: '' },
                    { id: 6, title: 'cặp sách công sở nam', url: '' },
                    { id: 7, title: 'ví cầm tay nam', url: '' },
                    {
                        id: 8,
                        title: 'túi đeo hông & túi đeo ngực nam',
                        url: '',
                    },
                    { id: 9, title: 'túi đeo chéo namnam', url: '' },
                    { id: 10, title: 'bóp/ ví nam', url: '' },
                    { id: 11, title: 'khác', url: '' },
                ],
            },
            {
                id: 6,
                category: 'voucher & dịch vụ',
                url: '',
                list: [
                    { id: 1, title: 'nhà hàng & ăn uống', url: '' },
                    { id: 2, title: 'sự kiện & giải trí', url: '' },
                    { id: 3, title: 'nạp tiền tài khoản', url: '' },
                    { id: 4, title: 'sức khỏe & làm đẹp', url: '' },
                    { id: 5, title: 'gọi xe', url: '' },
                    { id: 6, title: 'khóa học', url: '' },
                    { id: 7, title: 'du lịch & khác sạn', url: '' },
                    { id: 8, title: 'mua sắm', url: '' },
                    { id: 9, title: 'mã quà tặng shopee', url: '' },
                    { id: 10, title: 'thanh toán hóa đơn', url: '' },
                    { id: 11, title: 'dịch vụ khác', url: '' },
                ],
            },
        ],
    },
    {
        id: 2,
        colItem: [
            {
                id: 1,
                category: 'Thời trang nữ',
                url: '',
                list: [
                    { id: 1, title: 'quần', url: '' },
                    { id: 2, title: 'quần đùi', url: '' },
                    { id: 3, title: 'chân váy', url: '' },
                    { id: 4, title: 'quần jean', url: '' },
                    { id: 5, title: 'đầm/ váy', url: '' },
                    { id: 6, title: 'váy cưới', url: '' },
                    { id: 7, title: 'đồ liền thân', url: '' },
                    { id: 8, title: 'áo khoác, áo choàng & vest', url: '' },
                    { id: 9, title: 'áo len & cardigan', url: '' },
                    { id: 10, title: 'hoodie và áo nỉ', url: '' },
                    { id: 11, title: 'bộ', url: '' },
                    { id: 12, title: 'đồ lót', url: '' },
                    { id: 13, title: 'đồ ngủ', url: '' },
                    { id: 14, title: 'áo', url: '' },
                    { id: 15, title: 'đồ tập', url: '' },
                    { id: 16, title: 'đồ bầu', url: '' },
                    { id: 17, title: 'đồ truyền thống', url: '' },
                    { id: 18, title: 'đồ hoá trang', url: '' },
                    { id: 19, title: 'vải', url: '' },
                    { id: 20, title: 'vớ/ tất', url: '' },
                    { id: 21, title: 'khác', url: '' },
                ],
            },
            {
                id: 2,
                category: 'Máy tính & laptop',
                url: '',
                list: [
                    { id: 1, title: 'máy tính bàn', url: '' },
                    { id: 2, title: 'màn hình', url: '' },
                    { id: 3, title: 'linh kiện máy tính', url: '' },
                    { id: 4, title: 'thiết bị lưu trữ', url: '' },
                    { id: 5, title: 'thiết bị mạng', url: '' },
                    { id: 6, title: 'máy in, máy scan & máy chiếu', url: '' },
                    { id: 7, title: 'phụ kiện máy tính', url: '' },
                    { id: 8, title: 'laptop', url: '' },
                    { id: 9, title: 'khác', url: '' },
                    { id: 10, title: 'gaming', url: '' },
                ],
            },
            {
                id: 3,
                category: 'Giày dép nữ',
                url: '',
                list: [
                    { id: 1, title: 'bốt', url: '' },
                    { id: 2, title: 'giày thể thao/ sneaker', url: '' },
                    { id: 3, title: 'giày đế bằng', url: '' },
                    { id: 4, title: 'giày cao gót', url: '' },
                    { id: 5, title: 'giày đế xuồng', url: '' },
                    { id: 6, title: 'xăng-đan & dép', url: '' },
                    { id: 7, title: 'phụ kiện giày', url: '' },
                    { id: 8, title: 'giày khác ', url: '' },
                ],
            },
            {
                id: 4,
                category: 'thể thao & du lịch',
                url: '',
                list: [
                    { id: 1, title: 'vali', url: '' },
                    { id: 2, title: 'túi du lịch', url: '' },
                    { id: 3, title: 'phụ kiện du lịch', url: '' },
                    { id: 4, title: 'dụng cụ thể thao & dã ngoại', url: '' },
                    { id: 5, title: 'giày thể thao', url: '' },
                    {
                        id: 6,
                        title: 'thời trang thể thao & dã ngoại',
                        url: '',
                    },
                    { id: 7, title: 'phụ kiện thể thao & dã ngoại', url: '' },
                    { id: 8, title: 'khác', url: '' },
                ],
            },
            {
                id: 5,
                category: 'thời trang trẻ em',
                url: '',
                list: [
                    { id: 1, title: 'trang phục bé trai', url: '' },
                    { id: 2, title: 'trang phục bé gái', url: '' },
                    { id: 3, title: 'giày dép bé trai', url: '' },
                    { id: 4, title: 'giày dép bé gái', url: '' },
                    { id: 5, title: 'khác', url: '' },
                    { id: 6, title: 'quần áo em bé', url: '' },
                    { id: 7, title: 'giày tập đi & tất sơ sinh', url: '' },
                    { id: 8, title: 'phụ kiện trẻ em', url: '' },
                ],
            },
        ],
    },
    {
        id: 3,
        colItem: [
            {
                id: 1,
                category: 'điện thoại & phụ kiện',
                url: '',
                list: [
                    { id: 1, title: 'điện thoại', url: '' },
                    { id: 2, title: 'máy tính bảng', url: '' },
                    { id: 3, title: 'pin dự phòng', url: '' },
                    { id: 4, title: 'pin gắn trong, cáp và bộ sạc', url: '' },
                    {
                        id: 5,
                        title: 'ốp lưng, bao da, miếng dán điện thoại',
                        url: '',
                    },
                    { id: 6, title: 'bảo vệ màn hình', url: '' },
                    {
                        id: 7,
                        title: 'đế giữ điện thoại & gậy chụp hình',
                        url: '',
                    },
                    { id: 8, title: 'thẻ nhớ', url: '' },
                    { id: 9, title: 'sim', url: '' },
                    { id: 10, title: 'khác', url: '' },
                    { id: 11, title: 'điện thoại bàn', url: '' },
                ],
            },
            {
                id: 2,
                category: 'sắc đẹp',
                url: '',
                list: [
                    { id: 1, title: 'chăm sóc da mặt', url: '' },
                    { id: 2, title: 'tắm & chăm sóc cơ thể', url: '' },
                    { id: 3, title: 'trang điểm', url: '' },
                    { id: 4, title: 'chăm sóc tóc', url: '' },
                    { id: 5, title: 'dụng cụ & phụ kiện làm đẹp', url: '' },
                    { id: 6, title: 'vệ sinh răng miệng', url: '' },
                    { id: 7, title: 'nước hoa', url: '' },
                    { id: 8, title: 'chăm sóc nam giới', url: '' },
                    { id: 9, title: 'khác', url: '' },
                    { id: 10, title: 'chăm sóc phụ nữ', url: '' },
                    { id: 10, title: 'bộ sản phẩm làm đẹp', url: '' },
                ],
            },
            {
                id: 3,
                category: 'Giày dép nam',
                url: '',
                list: [
                    { id: 1, title: 'bốt', url: '' },
                    { id: 2, title: 'giày thể thao/ sneaker', url: '' },
                    { id: 3, title: 'giày sục', url: '' },
                    { id: 4, title: 'giày tây lười', url: '' },
                    { id: 5, title: 'giày oxfords & giày buộc dây', url: '' },
                    { id: 6, title: 'xăng-đan & dép', url: '' },
                    { id: 7, title: 'phụ kiện giày dép', url: '' },
                    { id: 8, title: 'khác', url: '' },
                ],
            },
            {
                id: 4,
                category: 'bách hoá online',
                url: '',
                list: [
                    { id: 1, title: 'đồ ăn vặt', url: '' },
                    { id: 2, title: 'đồ chế biến sẵn', url: '' },
                    { id: 3, title: 'nhu yếu phẩm', url: '' },
                    { id: 4, title: 'nguyên liệu nấu ăn', url: '' },
                    { id: 5, title: 'đồ làm bánh', url: '' },
                    { id: 6, title: 'sữa - trứng', url: '' },
                    { id: 7, title: 'đồ uống', url: '' },
                    { id: 8, title: 'ngũ cốc & mứt', url: '' },
                    { id: 9, title: 'các loại bánh', url: '' },
                    { id: 10, title: 'đồ uống có cồn', url: '' },
                    { id: 11, title: 'bộ quà tặng', url: '' },
                    {
                        id: 12,
                        title: 'Thực phẩm tươi sống và thực phẩm đông lạnh',
                        url: '',
                    },
                    { id: 13, title: 'khác', url: '' },
                ],
            },
            {
                id: 5,
                category: 'đồ chơi',
                url: '',
                list: [
                    { id: 1, title: 'đồ chơi mô hình', url: '' },
                    { id: 2, title: 'đồ chơi giải trí', url: '' },
                    { id: 3, title: 'đồ chơi giáo dục', url: '' },
                    {
                        id: 4,
                        title: 'đồ chơi cho trẻ sơ sinh & trẻ nhỏ',
                        url: '',
                    },
                    { id: 5, title: 'đồ chơi vận động & ngoài trời', url: '' },
                    { id: 6, title: 'búp bêp & đồ chơi nhồi bông', url: '' },
                ],
            },
        ],
    },
    {
        id: 4,
        colItem: [
            {
                id: 1,
                category: 'mẹ & bé',
                url: '',
                list: [
                    { id: 1, title: 'đồ dùng du lịch cho bé', url: '' },
                    { id: 2, title: 'đồ dùng ăn dặm cho bé', url: '' },
                    { id: 3, title: 'phụ kiện cho mẹ', url: '' },
                    { id: 4, title: 'chăm sóc sức khoẻ mẹ', url: '' },
                    {
                        id: 5,
                        title: 'đồ dùng phòng tắm & chăm sóc cơ thể bé',
                        url: '',
                    },
                    { id: 6, title: 'đồ dùng phòng ngủ cho bé', url: '' },
                    { id: 7, title: 'an toàn cho bé', url: '' },
                    { id: 8, title: 'thực phẩm cho bé', url: '' },
                    { id: 9, title: 'chăm sóc sức khoẻ bé', url: '' },
                    { id: 10, title: 'tã & bô em bé', url: '' },
                    { id: 11, title: 'đồ chơi', url: '' },
                    { id: 12, title: 'bộ & gói quà tặng', url: '' },
                    { id: 13, title: 'khác', url: '' },
                    { id: 14, title: 'sữa công thức trên 24 tháng', url: '' },
                    {
                        id: 15,
                        title: 'sữa công thức 0-24 tháng tuổi',
                        url: '',
                    },
                ],
            },
            {
                id: 2,
                category: 'máy ảnh & máy quay phim',
                url: '',
                list: [
                    { id: 1, title: 'máy ảnh & máy quay phim', url: '' },
                    {
                        id: 2,
                        title: 'camera giám sát & camera hệ thống',
                        url: '',
                    },
                    { id: 3, title: 'thẻ nhớ', url: '' },
                    { id: 4, title: 'ống kính', url: '' },
                    { id: 5, title: 'phụ kiện máy ảnh', url: '' },
                    { id: 6, title: 'báy bay camera & phụ kiện', url: '' },
                ],
            },
            {
                id: 3,
                category: 'túi ví nữ',
                url: '',
                list: [
                    { id: 1, title: 'ba lô nữ', url: '' },
                    { id: 2, title: 'cặp laptop', url: '' },
                    { id: 3, title: 'ví dự tiệc & ví cầm tay', url: '' },
                    { id: 4, title: 'túi đeo hông & túi đeo ngực', url: '' },
                    { id: 5, title: 'túi tote', url: '' },
                    { id: 6, title: 'túi quai xách', url: '' },
                    { id: 7, title: 'túi đeo chéo & túi đeo vai', url: '' },
                    { id: 8, title: 'ví/ bóp nữ', url: '' },
                    { id: 9, title: 'phụ kiện túi', url: '' },
                    { id: 10, title: 'khác', url: '' },
                ],
            },
            {
                id: 4,
                category: 'ô tô & xe máy & xe đạp ',
                url: '',
                list: [
                    { id: 1, title: 'xe đạp, xe điện', url: '' },
                    { id: 2, title: 'mô tô, xe máy', url: '' },
                    { id: 3, title: 'xe Ô tô', url: '' },
                    { id: 4, title: 'mũ bảo hiểm', url: '' },
                    { id: 5, title: 'phụ kiện xe máy', url: '' },
                    { id: 6, title: 'phụ kiện xe đạp', url: '' },
                    { id: 7, title: 'phụ kiện bên trong ô tô', url: '' },
                    { id: 8, title: 'dầu nhớt & dầu nhờn', url: '' },
                    { id: 9, title: 'phụ tùng ô tô', url: '' },
                    { id: 10, title: 'phụ tùng xe máy', url: '' },
                    { id: 11, title: 'phụ tùng bên ngoài ô tô', url: '' },
                    { id: 12, title: 'chăm sóc ô tô', url: '' },
                    { id: 13, title: 'dịch vụ cho xe', url: '' },
                ],
            },
            {
                id: 5,
                category: 'giặt giũ & chăm sóc nhà cửa',
                url: '',
                list: [
                    { id: 1, title: 'giặt giũ & chăm sóc nhà cửa', url: '' },
                    { id: 2, title: 'giấy vệ sinh, khăn giấy', url: '' },
                    { id: 3, title: 'vệ sinh nhà cửa', url: '' },
                    { id: 4, title: 'vệ sinh bát đĩa', url: '' },
                    { id: 5, title: 'dụng cụ vệ sinh', url: '' },
                    { id: 6, title: 'chất khử mùi, làm thơm', url: '' },
                    { id: 7, title: 'thuốc diệt côn trùng', url: '' },
                    { id: 8, title: 'túi, màng bọc thực phẩm', url: '' },
                    { id: 9, title: 'bao bì, túi đựng rác', url: '' },
                ],
            },
        ],
    },
    {
        id: 5,
        colItem: [
            {
                id: 1,
                category: 'thiết bị điện tử',
                url: '',
                list: [
                    { id: 1, title: 'thiết bị đeo thông minh', url: '' },
                    { id: 2, title: 'phụ kiện tv', url: '' },
                    { id: 3, title: 'máy game Console', url: '' },
                    { id: 4, title: 'Phụ kiện Console', url: '' },
                    { id: 5, title: 'đĩa game', url: '' },
                    { id: 6, title: 'linh phụ kiện', url: '' },
                    { id: 7, title: 'tai nghe', url: '' },
                    { id: 8, title: 'loa', url: '' },
                    { id: 9, title: 'tivi', url: '' },
                    { id: 10, title: 'tivi Box', url: '' },
                    { id: 11, title: 'tai nghe', url: '' },
                ],
            },
            {
                id: 2,
                category: 'sức khoẻ',
                url: '',
                list: [
                    { id: 1, title: 'vật tư y tế', url: '' },
                    {
                        id: 2,
                        title: 'chống muỗi & xua đuổi côn trùng',
                        url: '',
                    },
                    { id: 3, title: 'thực phẩm chức năng', url: '' },
                    { id: 4, title: 'tã người lớn', url: '' },
                    { id: 5, title: 'hỗ trợ làm đẹp', url: '' },
                    { id: 6, title: 'hỗ trợ tình dục', url: '' },
                    { id: 7, title: 'dụng cụ massage và trị liệu', url: '' },
                    { id: 8, title: 'khác', url: '' },
                ],
            },
            {
                id: 3,
                category: 'thiết bị điện da dụng',
                url: '',
                list: [
                    { id: 1, title: 'đồ gia dụng nhà bếp', url: '' },
                    { id: 2, title: 'đồ gia dụng lớn', url: '' },
                    {
                        id: 3,
                        title: 'máy hút bụi & thiết bị làm sạch',
                        url: '',
                    },
                    { id: 4, title: 'quạt & máy nóng lạnh', url: '' },
                    { id: 5, title: 'thiết bị chăm sóc quần áo', url: '' },
                    { id: 6, title: 'khác', url: '' },
                    {
                        id: 7,
                        title: 'máy xay, ép, máy đánh trứng trộn bột, máy xay thực phẩm',
                        url: '',
                    },
                    { id: 8, title: 'bếp điện', url: '' },
                ],
            },
            {
                id: 4,
                category: 'nhà sách online',
                url: '',
                list: [
                    { id: 1, title: 'sách tiếng việt', url: '' },
                    { id: 2, title: 'sách ngoại văn', url: '' },
                    { id: 3, title: 'gói quà', url: '' },
                    { id: 4, title: 'bút viết', url: '' },
                    { id: 5, title: 'dụng cụ học sinh & văn phòng', url: '' },
                    { id: 6, title: 'màu, hoạ cụ và đồ thủ công', url: '' },
                    { id: 7, title: 'sổ và giấy các loại', url: '' },
                    { id: 8, title: 'quà lưu niệm', url: '' },
                    { id: 9, title: 'nhạc cụ và phụ kiện âm nhạc', url: '' },
                ],
            },
            {
                id: 5,
                category: 'chăm sóc thú cưng',
                url: '',
                list: [
                    { id: 1, title: 'thức ăn cho thú cưng', url: '' },
                    { id: 2, title: 'phụ kiện cho thú cưng', url: '' },
                    { id: 3, title: 'vệ sinh cho thú cưng', url: '' },
                    { id: 4, title: 'quần áo cho thú cưng', url: '' },
                    { id: 5, title: 'chăm sóc sức khoẻ', url: '' },
                    { id: 6, title: 'làm đẹp cho thú cưng', url: '' },
                    { id: 7, title: 'khác', url: '' },
                ],
            },
        ],
    },
];

export const customersCare = [
    { id: 1, title: 'Trung tâm trợ giúp', url: '' },
    { id: 2, title: 'Shopee Blog', url: '' },
    { id: 3, title: 'Shopee Mail', url: '' },
    { id: 4, title: 'Hướng dẫn mua hàng', url: '' },
    { id: 5, title: 'Hướng dẫn bán hàng', url: '' },
    { id: 6, title: 'Thanh toán', url: '' },
    { id: 7, title: 'Shopee xu', url: '' },
    { id: 8, title: 'Vận chuyển', url: '' },
    { id: 9, title: 'Trả hàng & hoàn tiền', url: '' },
    { id: 10, title: 'Chăm sóc khách hàng', url: '' },
    { id: 11, title: 'Chính sách bảo hành', url: '' },
];

export const aboutUs = [
    { id: 1, title: 'Giới thiệu về shopee việt nam', url: '' },
    { id: 2, title: 'Tuyển dụng', url: '' },
    { id: 3, title: 'Điều khoản shopee', url: '' },
    { id: 4, title: 'Chính sách bảo mật', url: '' },
    { id: 5, title: 'Chính hãng', url: '' },
    { id: 6, title: 'Kênh người bán', url: '' },
    { id: 7, title: 'Flash sales', url: '' },
    { id: 8, title: 'Chương trình tiếp thị liên kết shopee', url: '' },
    { id: 9, title: 'Liên hệ với truyền thông', url: '' },
];

export const paymentMethod = [
    {
        id: 1,
        title: '',
        url: 'https://cf.shopee.vn/file/d4bbea4570b93bfd5fc652ca82a262a8',
    },
    {
        id: 2,
        title: '',
        url: 'https://cf.shopee.vn/file/a0a9062ebe19b45c1ae0506f16af5c16',
    },
    {
        id: 3,
        title: '',
        url: 'https://cf.shopee.vn/file/38fd98e55806c3b2e4535c4e4a6c4c08',
    },
    {
        id: 4,
        title: '',
        url: 'https://cf.shopee.vn/file/bc2a874caeee705449c164be385b796c',
    },
    {
        id: 5,
        title: '',
        url: 'https://cf.shopee.vn/file/2c46b83d84111ddc32cfd3b5995d9281',
    },
    {
        id: 6,
        title: '',
        url: 'https://cf.shopee.vn/file/5e3f0bee86058637ff23cfdf2e14ca09',
    },
    {
        id: 7,
        title: '',
        url: 'https://cf.shopee.vn/file/9263fa8c83628f5deff55e2a90758b06',
    },
    {
        id: 8,
        title: '',
        url: 'https://cf.shopee.vn/file/0217f1d345587aa0a300e69e2195c492',
    },
];

export const transportMethod = [
    {
        id: 1,
        title: '',
        url: 'https://cf.shopee.vn/file/5e7282bd0f7ee0872fdb0bd1d40fbe9e',
    },
    {
        id: 2,
        title: '',
        url: 'https://cf.shopee.vn/file/d10b0ec09f0322f9201a4f3daf378ed2',
    },
    {
        id: 3,
        title: '',
        url: 'https://cf.shopee.vn/file/77bf96a871418fbc21cc63dd39fb5f15',
    },
    {
        id: 4,
        title: '',
        url: 'https://cf.shopee.vn/file/59270fb2f3fbb7cbc92fca3877edde3f',
    },
    {
        id: 5,
        title: '',
        url: 'https://cf.shopee.vn/file/957f4eec32b963115f952835c779cd2c',
    },
    {
        id: 6,
        title: '',
        url: 'https://cf.shopee.vn/file/0d349e22ca8d4337d11c9b134cf9fe63',
    },
    {
        id: 7,
        title: '',
        url: 'https://cf.shopee.vn/file/3900aefbf52b1c180ba66e5ec91190e5',
    },
    {
        id: 8,
        title: '',
        url: 'https://cf.shopee.vn/file/957f4eec32b963115f952835c779cd2c',
    },
    {
        id: 9,
        title: '',
        url: 'https://cf.shopee.vn/file/b8348201b4611fc3315b82765d35fc63',
    },
    {
        id: 10,
        title: '',
        url: 'https://cf.shopee.vn/file/864825c06b9f2c8c9334ebdeafa1f0fb',
    },
];

export const followUs = [
    {
        id: 1,
        title: 'facebook',
        thumbnail: '',
        url: 'https://www.facebook.com/ShopeeVN',
    },
    {
        id: 2,
        title: 'instagram',
        thumbnail: '',
        url: 'https://www.instagram.com/Shopee_VN/',
    },
    {
        id: 3,
        title: 'linkedln',
        thumbnail: 'linkedin',
        url: 'https://www.linkedin.com/company/shopee',
    },
];

export const regionShopee = [
    { id: 1, title: 'singapore', url: 'https://shopee.sg/' },
    { id: 2, title: 'indonesia', url: 'https://shopee.co.id/' },
    { id: 3, title: 'đài loan', url: 'https://shopee.tw/' },
    { id: 4, title: 'thái lan', url: 'https://shopee.co.th/' },
    { id: 5, title: 'malaysia', url: 'https://shopee.com.my/' },
    { id: 6, title: 'việt nam', url: 'https://shopee.vn/' },
    { id: 7, title: 'philippines', url: 'https://shopee.ph/' },
    { id: 8, title: 'brazil', url: 'https://shopee.com.br/' },
    { id: 9, title: 'méxico', url: 'https://shopee.com.mx/' },
    { id: 10, title: 'colombia', url: 'https://shopee.com.co/' },
    { id: 11, title: 'chile', url: 'https://shopee.cl/' },
    { id: 12, title: 'poland', url: 'https://shopee.pl/' },
    { id: 13, title: 'argentina', url: 'https://shopee.com.ar/' },
];
