export const footerCategory = [
    {
        id: 1,
        colItem: [
            {
                id: 1,
                category: 'Thời trang nam',
                link: '',
                list: [
                    { id: 1, title: 'áo khoác', link: '' },
                    { id: 2, title: 'áo vest & blazer', link: '' },
                    { id: 3, title: 'áo hoodie, áo len & áo nỉ', link: '' },
                    { id: 4, title: 'quần jeans', link: '' },
                    { id: 5, title: 'quần dài/quần âu', link: '' },
                    { id: 6, title: 'quần short', link: '' },
                    { id: 7, title: 'áo', link: '' },
                    { id: 8, title: 'áo ba lỗ', link: '' },
                    { id: 9, title: 'đồ lót', link: '' },
                    { id: 10, title: 'đồ ngủ', link: '' },
                    { id: 11, title: 'đồ bộ', link: '' },
                    { id: 12, title: 'vớ/tất', link: '' },
                    { id: 13, title: 'trang phục truyền thống', link: '' },
                    { id: 14, title: 'đồ hóa trang', link: '' },
                    { id: 15, title: 'trang phục ngành nghề', link: '' },
                    { id: 16, title: 'khác', link: '' },
                    { id: 17, title: 'trang sức nam', link: '' },
                    { id: 18, title: 'kính mắt nam', link: '' },
                    { id: 19, title: 'thắt lưng nam', link: '' },
                    { id: 20, title: 'cà vạt & nơ cổ', link: '' },
                    { id: 21, title: 'phụ kiện nam', link: '' },
                ],
            },
            {
                id: 2,
                category: 'Nhà cửa và đời sống',
                link: '',
                list: [
                    { id: 1, title: 'chăn, ga, gối & nệm', link: '' },
                    { id: 2, title: 'đồ nội thất', link: '' },
                    { id: 3, title: 'trang trí nhà cửa', link: '' },
                    { id: 4, title: 'dụng cụ & thiết bị tiện ích', link: '' },
                    {
                        id: 5,
                        title: 'đồ dùng nhà bếp và hộp đựng thực phẩm',
                        link: '',
                    },
                    { id: 6, title: 'đèn', link: '' },
                    { id: 7, title: 'ngoài trời & sân vườn', link: '' },
                    { id: 8, title: 'đồ dùng phòng tắm', link: '' },
                    { id: 9, title: 'vật phẩm thờ cúng', link: '' },
                    { id: 10, title: 'đồ trang trí tiệc', link: '' },
                    { id: 11, title: 'chăm sóc nhà cửa và giặt ủi', link: '' },
                    { id: 12, title: 'sắp xếp nhà cửa', link: '' },
                    { id: 13, title: 'dụng cụ pha chế', link: '' },
                    { id: 14, title: 'tinh dầu thơm phòng', link: '' },
                    { id: 15, title: 'đồ dùng phòng ăn', link: '' },
                ],
            },
            {
                id: 3,
                category: 'Đồng hồ',
                link: '',
                list: [
                    { id: 1, title: 'đồng hồ nam', link: '' },
                    { id: 2, title: 'đồng hồ nữ', link: '' },
                    { id: 3, title: 'bộ đồng hồ & đồng hồ cặp', link: '' },
                    { id: 4, title: 'đồng hồ trẻ em', link: '' },
                    { id: 5, title: 'phụ kiện đồng hồ', link: '' },
                    { id: 6, title: 'khác', link: '' },
                ],
            },
            {
                id: 4,
                category: 'phụ kiện & trang sức nữ',
                link: '',
                list: [
                    { id: 1, title: 'nhẫn', link: '' },
                    { id: 2, title: 'bông tai', link: '' },
                    { id: 3, title: 'khăn choàng', link: '' },
                    { id: 4, title: 'găng tay', link: '' },
                    { id: 5, title: 'phụ kiện tóc', link: '' },
                    { id: 6, title: 'vòng tay & lắc tay', link: '' },
                    { id: 7, title: 'lắc chân', link: '' },
                    { id: 8, title: 'mũ', link: '' },
                    { id: 9, title: 'dây chuyền', link: '' },
                    { id: 10, title: 'kính mắt', link: '' },
                    { id: 11, title: 'kim loại quý', link: '' },
                    { id: 12, title: 'thắt lưng', link: '' },
                    { id: 13, title: 'và vạt & nơ cổ', link: '' },
                    { id: 14, title: 'phụ kiện thêm', link: '' },
                    { id: 15, title: 'bộ phụ kiện', link: '' },
                    { id: 16, title: 'vớ/ tất', link: '' },
                    { id: 17, title: 'ô/ dù', link: '' },
                ],
            },
            {
                id: 5,
                category: 'balo & túi ví nam',
                link: '',
                list: [
                    { id: 1, title: 'ba lô nam', link: '' },
                    { id: 2, title: 'ba lô laptop nam', link: '' },
                    { id: 3, title: 'túi & cặp đựng laptop', link: '' },
                    { id: 4, title: 'túi chống sốc laptop nam', link: '' },
                    { id: 5, title: 'túi tote nam', link: '' },
                    { id: 6, title: 'cặp sách công sở nam', link: '' },
                    { id: 7, title: 'ví cầm tay nam', link: '' },
                    {
                        id: 8,
                        title: 'túi đeo hông & túi đeo ngực nam',
                        link: '',
                    },
                    { id: 9, title: 'túi đeo chéo namnam', link: '' },
                    { id: 10, title: 'bóp/ ví nam', link: '' },
                    { id: 11, title: 'khác', link: '' },
                ],
            },
            {
                id: 6,
                category: 'voucher & dịch vụ',
                link: '',
                list: [
                    { id: 1, title: 'nhà hàng & ăn uống', link: '' },
                    { id: 2, title: 'sự kiện & giải trí', link: '' },
                    { id: 3, title: 'nạp tiền tài khoản', link: '' },
                    { id: 4, title: 'sức khỏe & làm đẹp', link: '' },
                    { id: 5, title: 'gọi xe', link: '' },
                    { id: 6, title: 'khóa học', link: '' },
                    { id: 7, title: 'du lịch & khác sạn', link: '' },
                    { id: 8, title: 'mua sắm', link: '' },
                    { id: 9, title: 'mã quà tặng shopee', link: '' },
                    { id: 10, title: 'thanh toán hóa đơn', link: '' },
                    { id: 11, title: 'dịch vụ khác', link: '' },
                ],
            },
        ],
    },
    {
        id: 2,
        colItem: [
            {
                id: 1,
                category: 'Thời trang nữ',
                link: '',
                list: [
                    { id: 1, title: 'quần', link: '' },
                    { id: 2, title: 'quần đùi', link: '' },
                    { id: 3, title: 'chân váy', link: '' },
                    { id: 4, title: 'quần jean', link: '' },
                    { id: 5, title: 'đầm/ váy', link: '' },
                    { id: 6, title: 'váy cưới', link: '' },
                    { id: 7, title: 'đồ liền thân', link: '' },
                    { id: 8, title: 'áo khoác, áo choàng & vest', link: '' },
                    { id: 9, title: 'áo len & cardigan', link: '' },
                    { id: 10, title: 'hoodie và áo nỉ', link: '' },
                    { id: 11, title: 'bộ', link: '' },
                    { id: 12, title: 'đồ lót', link: '' },
                    { id: 13, title: 'đồ ngủ', link: '' },
                    { id: 14, title: 'áo', link: '' },
                    { id: 15, title: 'đồ tập', link: '' },
                    { id: 16, title: 'đồ bầu', link: '' },
                    { id: 17, title: 'đồ truyền thống', link: '' },
                    { id: 18, title: 'đồ hoá trang', link: '' },
                    { id: 19, title: 'vải', link: '' },
                    { id: 20, title: 'vớ/ tất', link: '' },
                    { id: 21, title: 'khác', link: '' },
                ],
            },
            {
                id: 2,
                category: 'Máy tính & laptop',
                link: '',
                list: [
                    { id: 1, title: 'máy tính bàn', link: '' },
                    { id: 2, title: 'màn hình', link: '' },
                    { id: 3, title: 'linh kiện máy tính', link: '' },
                    { id: 4, title: 'thiết bị lưu trữ', link: '' },
                    { id: 5, title: 'thiết bị mạng', link: '' },
                    { id: 6, title: 'máy in, máy scan & máy chiếu', link: '' },
                    { id: 7, title: 'phụ kiện máy tính', link: '' },
                    { id: 8, title: 'laptop', link: '' },
                    { id: 9, title: 'khác', link: '' },
                    { id: 10, title: 'gaming', link: '' },
                ],
            },
            {
                id: 3,
                category: 'Giày dép nữ',
                link: '',
                list: [
                    { id: 1, title: 'bốt', link: '' },
                    { id: 2, title: 'giày thể thao/ sneaker', link: '' },
                    { id: 3, title: 'giày đế bằng', link: '' },
                    { id: 4, title: 'giày cao gót', link: '' },
                    { id: 5, title: 'giày đế xuồng', link: '' },
                    { id: 6, title: 'xăng-đan & dép', link: '' },
                    { id: 7, title: 'phụ kiện giày', link: '' },
                    { id: 8, title: 'giày khác ', link: '' },
                ],
            },
            {
                id: 4,
                category: 'thể thao & du lịch',
                link: '',
                list: [
                    { id: 1, title: 'vali', link: '' },
                    { id: 2, title: 'túi du lịch', link: '' },
                    { id: 3, title: 'phụ kiện du lịch', link: '' },
                    { id: 4, title: 'dụng cụ thể thao & dã ngoại', link: '' },
                    { id: 5, title: 'giày thể thao', link: '' },
                    {
                        id: 6,
                        title: 'thời trang thể thao & dã ngoại',
                        link: '',
                    },
                    { id: 7, title: 'phụ kiện thể thao & dã ngoại', link: '' },
                    { id: 8, title: 'khác', link: '' },
                ],
            },
            {
                id: 5,
                category: 'thời trang trẻ em',
                link: '',
                list: [
                    { id: 1, title: 'trang phục bé trai', link: '' },
                    { id: 2, title: 'trang phục bé gái', link: '' },
                    { id: 3, title: 'giày dép bé trai', link: '' },
                    { id: 4, title: 'giày dép bé gái', link: '' },
                    { id: 5, title: 'khác', link: '' },
                    { id: 6, title: 'quần áo em bé', link: '' },
                    { id: 7, title: 'giày tập đi & tất sơ sinh', link: '' },
                    { id: 8, title: 'phụ kiện trẻ em', link: '' },
                ],
            },
        ],
    },
    {
        id: 3,
        colItem: [
            {
                id: 1,
                category: 'điện thoại & phụ kiện',
                link: '',
                list: [
                    { id: 1, title: 'điện thoại', link: '' },
                    { id: 2, title: 'máy tính bảng', link: '' },
                    { id: 3, title: 'pin dự phòng', link: '' },
                    { id: 4, title: 'pin gắn trong, cáp và bộ sạc', link: '' },
                    {
                        id: 5,
                        title: 'ốp lưng, bao da, miếng dán điện thoại',
                        link: '',
                    },
                    { id: 6, title: 'bảo vệ màn hình', link: '' },
                    {
                        id: 7,
                        title: 'đế giữ điện thoại & gậy chụp hình',
                        link: '',
                    },
                    { id: 8, title: 'thẻ nhớ', link: '' },
                    { id: 9, title: 'sim', link: '' },
                    { id: 10, title: 'khác', link: '' },
                    { id: 11, title: 'điện thoại bàn', link: '' },
                ],
            },
            {
                id: 2,
                category: 'sắc đẹp',
                link: '',
                list: [
                    { id: 1, title: 'chăm sóc da mặt', link: '' },
                    { id: 2, title: 'tắm & chăm sóc cơ thể', link: '' },
                    { id: 3, title: 'trang điểm', link: '' },
                    { id: 4, title: 'chăm sóc tóc', link: '' },
                    { id: 5, title: 'dụng cụ & phụ kiện làm đẹp', link: '' },
                    { id: 6, title: 'vệ sinh răng miệng', link: '' },
                    { id: 7, title: 'nước hoa', link: '' },
                    { id: 8, title: 'chăm sóc nam giới', link: '' },
                    { id: 9, title: 'khác', link: '' },
                    { id: 10, title: 'chăm sóc phụ nữ', link: '' },
                    { id: 10, title: 'bộ sản phẩm làm đẹp', link: '' },
                ],
            },
            {
                id: 3,
                category: 'Giày dép nam',
                link: '',
                list: [
                    { id: 1, title: 'bốt', link: '' },
                    { id: 2, title: 'giày thể thao/ sneaker', link: '' },
                    { id: 3, title: 'giày sục', link: '' },
                    { id: 4, title: 'giày tây lười', link: '' },
                    { id: 5, title: 'giày oxfords & giày buộc dây', link: '' },
                    { id: 6, title: 'xăng-đan & dép', link: '' },
                    { id: 7, title: 'phụ kiện giày dép', link: '' },
                    { id: 8, title: 'khác', link: '' },
                ],
            },
            {
                id: 4,
                category: 'bách hoá online',
                link: '',
                list: [
                    { id: 1, title: 'đồ ăn vặt', link: '' },
                    { id: 2, title: 'đồ chế biến sẵn', link: '' },
                    { id: 3, title: 'nhu yếu phẩm', link: '' },
                    { id: 4, title: 'nguyên liệu nấu ăn', link: '' },
                    { id: 5, title: 'đồ làm bánh', link: '' },
                    { id: 6, title: 'sữa - trứng', link: '' },
                    { id: 7, title: 'đồ uống', link: '' },
                    { id: 8, title: 'ngũ cốc & mứt', link: '' },
                    { id: 9, title: 'các loại bánh', link: '' },
                    { id: 10, title: 'đồ uống có cồn', link: '' },
                    { id: 11, title: 'bộ quà tặng', link: '' },
                    {
                        id: 12,
                        title: 'Thực phẩm tươi sống và thực phẩm đông lạnh',
                        link: '',
                    },
                    { id: 13, title: 'khác', link: '' },
                ],
            },
            {
                id: 5,
                category: 'đồ chơi',
                link: '',
                list: [
                    { id: 1, title: 'đồ chơi mô hình', link: '' },
                    { id: 2, title: 'đồ chơi giải trí', link: '' },
                    { id: 3, title: 'đồ chơi giáo dục', link: '' },
                    {
                        id: 4,
                        title: 'đồ chơi cho trẻ sơ sinh & trẻ nhỏ',
                        link: '',
                    },
                    { id: 5, title: 'đồ chơi vận động & ngoài trời', link: '' },
                    { id: 6, title: 'búp bêp & đồ chơi nhồi bông', link: '' },
                ],
            },
        ],
    },
    {
        id: 4,
        colItem: [
            {
                id: 1,
                category: 'mẹ & bé',
                link: '',
                list: [
                    { id: 1, title: 'đồ dùng du lịch cho bé', link: '' },
                    { id: 2, title: 'đồ dùng ăn dặm cho bé', link: '' },
                    { id: 3, title: 'phụ kiện cho mẹ', link: '' },
                    { id: 4, title: 'chăm sóc sức khoẻ mẹ', link: '' },
                    {
                        id: 5,
                        title: 'đồ dùng phòng tắm & chăm sóc cơ thể bé',
                        link: '',
                    },
                    { id: 6, title: 'đồ dùng phòng ngủ cho bé', link: '' },
                    { id: 7, title: 'an toàn cho bé', link: '' },
                    { id: 8, title: 'thực phẩm cho bé', link: '' },
                    { id: 9, title: 'chăm sóc sức khoẻ bé', link: '' },
                    { id: 10, title: 'tã & bô em bé', link: '' },
                    { id: 11, title: 'đồ chơi', link: '' },
                    { id: 12, title: 'bộ & gói quà tặng', link: '' },
                    { id: 13, title: 'khác', link: '' },
                    { id: 14, title: 'sữa công thức trên 24 tháng', link: '' },
                    {
                        id: 15,
                        title: 'sữa công thức 0-24 tháng tuổi',
                        link: '',
                    },
                ],
            },
            {
                id: 2,
                category: 'máy ảnh & máy quay phim',
                link: '',
                list: [
                    { id: 1, title: 'máy ảnh & máy quay phim', link: '' },
                    {
                        id: 2,
                        title: 'camera giám sát & camera hệ thống',
                        link: '',
                    },
                    { id: 3, title: 'thẻ nhớ', link: '' },
                    { id: 4, title: 'ống kính', link: '' },
                    { id: 5, title: 'phụ kiện máy ảnh', link: '' },
                    { id: 6, title: 'báy bay camera & phụ kiện', link: '' },
                ],
            },
            {
                id: 3,
                category: 'túi ví nữ',
                link: '',
                list: [
                    { id: 1, title: 'ba lô nữ', link: '' },
                    { id: 2, title: 'cặp laptop', link: '' },
                    { id: 3, title: 'ví dự tiệc & ví cầm tay', link: '' },
                    { id: 4, title: 'túi đeo hông & túi đeo ngực', link: '' },
                    { id: 5, title: 'túi tote', link: '' },
                    { id: 6, title: 'túi quai xách', link: '' },
                    { id: 7, title: 'túi đeo chéo & túi đeo vai', link: '' },
                    { id: 8, title: 'ví/ bóp nữ', link: '' },
                    { id: 9, title: 'phụ kiện túi', link: '' },
                    { id: 10, title: 'khác', link: '' },
                ],
            },
            {
                id: 4,
                category: 'ô tô & xe máy & xe đạp ',
                link: '',
                list: [
                    { id: 1, title: 'xe đạp, xe điện', link: '' },
                    { id: 2, title: 'mô tô, xe máy', link: '' },
                    { id: 3, title: 'xe Ô tô', link: '' },
                    { id: 4, title: 'mũ bảo hiểm', link: '' },
                    { id: 5, title: 'phụ kiện xe máy', link: '' },
                    { id: 6, title: 'phụ kiện xe đạp', link: '' },
                    { id: 7, title: 'phụ kiện bên trong ô tô', link: '' },
                    { id: 8, title: 'dầu nhớt & dầu nhờn', link: '' },
                    { id: 9, title: 'phụ tùng ô tô', link: '' },
                    { id: 10, title: 'phụ tùng xe máy', link: '' },
                    { id: 11, title: 'phụ tùng bên ngoài ô tô', link: '' },
                    { id: 12, title: 'chăm sóc ô tô', link: '' },
                    { id: 13, title: 'dịch vụ cho xe', link: '' },
                ],
            },
            {
                id: 5,
                category: 'giặt giũ & chăm sóc nhà cửa',
                link: '',
                list: [
                    { id: 1, title: 'giặt giũ & chăm sóc nhà cửa', link: '' },
                    { id: 2, title: 'giấy vệ sinh, khăn giấy', link: '' },
                    { id: 3, title: 'vệ sinh nhà cửa', link: '' },
                    { id: 4, title: 'vệ sinh bát đĩa', link: '' },
                    { id: 5, title: 'dụng cụ vệ sinh', link: '' },
                    { id: 6, title: 'chất khử mùi, làm thơm', link: '' },
                    { id: 7, title: 'thuốc diệt côn trùng', link: '' },
                    { id: 8, title: 'túi, màng bọc thực phẩm', link: '' },
                    { id: 9, title: 'bao bì, túi đựng rác', link: '' },
                ],
            },
        ],
    },
    {
        id: 5,
        colItem: [
            {
                id: 1,
                category: 'thiết bị điện tử',
                link: '',
                list: [
                    { id: 1, title: 'thiết bị đeo thông minh', link: '' },
                    { id: 2, title: 'phụ kiện tv', link: '' },
                    { id: 3, title: 'máy game Console', link: '' },
                    { id: 4, title: 'Phụ kiện Console', link: '' },
                    { id: 5, title: 'đĩa game', link: '' },
                    { id: 6, title: 'linh phụ kiện', link: '' },
                    { id: 7, title: 'tai nghe', link: '' },
                    { id: 8, title: 'loa', link: '' },
                    { id: 9, title: 'tivi', link: '' },
                    { id: 10, title: 'tivi Box', link: '' },
                    { id: 11, title: 'tai nghe', link: '' },
                ],
            },
            {
                id: 2,
                category: 'sức khoẻ',
                link: '',
                list: [
                    { id: 1, title: 'vật tư y tế', link: '' },
                    {
                        id: 2,
                        title: 'chống muỗi & xua đuổi côn trùng',
                        link: '',
                    },
                    { id: 3, title: 'thực phẩm chức năng', link: '' },
                    { id: 4, title: 'tã người lớn', link: '' },
                    { id: 5, title: 'hỗ trợ làm đẹp', link: '' },
                    { id: 6, title: 'hỗ trợ tình dục', link: '' },
                    { id: 7, title: 'dụng cụ massage và trị liệu', link: '' },
                    { id: 8, title: 'khác', link: '' },
                ],
            },
            {
                id: 3,
                category: 'thiết bị điện da dụng',
                link: '',
                list: [
                    { id: 1, title: 'đồ gia dụng nhà bếp', link: '' },
                    { id: 2, title: 'đồ gia dụng lớn', link: '' },
                    {
                        id: 3,
                        title: 'máy hút bụi & thiết bị làm sạch',
                        link: '',
                    },
                    { id: 4, title: 'quạt & máy nóng lạnh', link: '' },
                    { id: 5, title: 'thiết bị chăm sóc quần áo', link: '' },
                    { id: 6, title: 'khác', link: '' },
                    {
                        id: 7,
                        title: 'máy xay, ép, máy đánh trứng trộn bột, máy xay thực phẩm',
                        link: '',
                    },
                    { id: 8, title: 'bếp điện', link: '' },
                ],
            },
            {
                id: 4,
                category: 'nhà sách online',
                link: '',
                list: [
                    { id: 1, title: 'sách tiếng việt', link: '' },
                    { id: 2, title: 'sách ngoại văn', link: '' },
                    { id: 3, title: 'gói quà', link: '' },
                    { id: 4, title: 'bút viết', link: '' },
                    { id: 5, title: 'dụng cụ học sinh & văn phòng', link: '' },
                    { id: 6, title: 'màu, hoạ cụ và đồ thủ công', link: '' },
                    { id: 7, title: 'sổ và giấy các loại', link: '' },
                    { id: 8, title: 'quà lưu niệm', link: '' },
                    { id: 9, title: 'nhạc cụ và phụ kiện âm nhạc', link: '' },
                ],
            },
            {
                id: 5,
                category: 'chăm sóc thú cưng',
                link: '',
                list: [
                    { id: 1, title: 'thức ăn cho thú cưng', link: '' },
                    { id: 2, title: 'phụ kiện cho thú cưng', link: '' },
                    { id: 3, title: 'vệ sinh cho thú cưng', link: '' },
                    { id: 4, title: 'quần áo cho thú cưng', link: '' },
                    { id: 5, title: 'chăm sóc sức khoẻ', link: '' },
                    { id: 6, title: 'làm đẹp cho thú cưng', link: '' },
                    { id: 7, title: 'khác', link: '' },
                ],
            },
        ],
    },
];
